// <auto-generated />
namespace PizzaNetDataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class ForeingKeyschanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForeingKeyschanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201310260958377_Foreing Keys changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
